var appConst={
	"user.username":'用户名要求为非空字符,且长度在4至32位之间'	,
	"user.username.confirm":'用户名已存在，请重新输入'	,
	"user.password":'密码要求为非空字符,且长度在6至36位之间',
	"user.confirm.password":'确认密码不一致,请重新输入',
	"resource.viewType":'请选择资源类型',
	"resource.item.type":'请选择资源项目类型',
	"role.authority":"权限要求小于128位的字符",
	"dict.category.categoryCode":"类别编码要求2位字符",
	"dict.category.item":"要求不少于一项数据字典",
	"main.message.waiting":"你有{0}条未读消息.",
	"broadcast.delete":"是否确认删除该条广播？",
	"broadcast.check":"您输入的字数不能少于{0}个，请重新输入",
	"broadcast.add":"是否发布此广播？",
	"broadcast.edit":"是否重新发布此广播？",
	"ownersManager.resetpwd":"是否确定重置密码？",
	"ownersManager.resetSuccess":"重置密码成功！",
	"xbquotations.delete":"是否确认删除?",
	"albumManager.addSubscription":"是否加入订阅?",
	"albumManager.cancelSubscription":"是否取消订阅?",
	"xbquotations.submit":"是否确认提交?",
	"albumManager.submit":"是否确认提交?",
	"musicmanager.edit":"是否确认提交?",
	"xiamimusicmanager.download":"是否确认下载?"
		
};
