var MusicManager={
		"MSG_MusicManager_005":"{0} !",
		"MSG_MusicManager_006":"确认{0}？",
		"MSG_MusicManager_014":"请选择{0}。",
		"MSG_MusicManager_007":"删除成功。",
		"MSG_MusicManager_008":"新增音乐成功!",
		"MSG_MusicManager_014":"新增音乐失败!",
		"MSG_MusicManager_009":"修改音乐成功!",
		"MSG_MusicManager_015":"修改音乐失败!",
		"MSG_MusicManager_010":"请至少选择一条声讯信息!",
		"MSG_MusicManager_011":"用户名不能为空。",
		"MSG_MusicManager_012":"密码不能为空或者密码不一致。",
		"MSG_MusicManager_013":"删除失败!",
		"MSG_MusicManager_016":"标签添加成功!",
		"MSG_MusicManager_017":"标签添加失败!",
		"MSG_MusicManager_018":"标签修改失败!",
		"MSG_MusicManager_019":"标签修改成功!",
		"MSG_MusicManager_020":"请选择需要删除的标签!",
		"MSG_MusicManager_021":"请输入查询条件!",
		"MSG_MusicManager_022":"下载音乐成功!",
		"MSG_MusicManager_023":"下载音乐失败!"
};